# Generated by Django 4.2.4 on 2023-08-27 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rnr.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNRRoomCompare',
            fields=[
                ('id', models.UUIDField(default=rnr.models.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
