# Generated by Django 4.2.4 on 2023-08-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0002_rnrroomcompare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RNRRoomCompare',
        ),
    ]
