# Generated by Django 4.2.4 on 2023-08-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnr', '0003_delete_rnrroomcompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNRRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.FloatField()),
                ('rnr_transaction_code', models.CharField(max_length=2040)),
                ('currency', models.CharField(max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
