# Generated by Django 4.2.4 on 2023-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0004_rnrroomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnrroomreservation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
