# Generated by Django 4.2.4 on 2023-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0005_rnrroomreservation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnrroomreservation',
            name='rnr_transaction_code',
            field=models.CharField(max_length=2040, null=True),
        ),
    ]
