# Generated by Django 4.2.4 on 2023-08-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0007_rnrroomreservationrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnrroomreservation',
            name='mer_txid',
            field=models.CharField(max_length=2040, null=True),
        ),
        migrations.AddField(
            model_name='rnrroomreservation',
            name='pg_txid',
            field=models.CharField(max_length=2040, null=True),
        ),
        migrations.AlterField(
            model_name='rnrroomreservationrefund',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rnr.rnrroomreservation'),
        ),
    ]
