# Generated by Django 4.2.4 on 2023-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0009_alter_rnrroomreservation_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnrroomreservation',
            name='property_id',
            field=models.CharField(max_length=2040000),
        ),
        migrations.AlterField(
            model_name='rnrroomreservation',
            name='reservation_id',
            field=models.CharField(max_length=2040000),
        ),
    ]
