# Generated by Django 4.2.4 on 2023-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnr', '0010_alter_rnrroomreservation_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnrroomreservation',
            name='rooms',
            field=models.JSONField(default=dict),
        ),
    ]
