# Generated by Django 4.2.10 on 2024-02-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
        ("rnr", "0012_rnrroomreservation_guest_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoomPurchaseHistory",
            fields=[
                (
                    "pg_payment_request_log",
                    models.OneToOneField(
                        error_messages={
                            "null": "the payment request must be provided",
                            "unique": "the request instance must be unique",
                        },
                        help_text="the pg payment request from which the purchase history was generated",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        related_name="purchase_history_pg_payment_request",
                        serialize=False,
                        to="payment.pgpaymentrequestlog",
                        verbose_name="pg payment request",
                    ),
                ),
                (
                    "reservation_id",
                    models.CharField(
                        error_messages={"null": "The Rnr room reservation id cannot be null"},
                        help_text="The Rnr room reservation id that is purchased by this user",
                        max_length=200,
                        verbose_name="The Rnr room reservation id",
                    ),
                ),
                (
                    "purchase_status",
                    models.CharField(
                        choices=[("SUCC", "Successful"), ("FAIL", "Failed")],
                        default="FAIL",
                        error_messages={"null": "purchase status cannot be null"},
                        help_text="The purchase status of the package",
                        max_length=5,
                        verbose_name="purchase status",
                    ),
                ),
                (
                    "purchase_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the purchase was made",
                        verbose_name="purchase at",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Room Purchase History",
                "verbose_name_plural": "User Room Purchase Histories",
                "db_table_comment": "User Room Purchase History",
                "ordering": ["-purchase_timestamp"],
            },
        ),
    ]
