# Generated by Django 4.2.10 on 2024-02-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
        ("rnr", "0013_userroompurchasehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoomPurchaseConfirmResponseLog",
            fields=[
                (
                    "user_transaction",
                    models.OneToOneField(
                        error_messages={
                            "null": "user transaction must be provided",
                            "unique": "user transaction instance must be unique",
                        },
                        help_text="the user transaction from which the response was generated",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        related_name="room_purchase_res_user_transaction",
                        serialize=False,
                        to="payment.usertransaction",
                        verbose_name="user transaction",
                    ),
                ),
                (
                    "api_response",
                    models.JSONField(
                        error_messages={
                            "blank": "activate package api response data must be provided"
                        },
                        help_text="activate package api response data",
                        null=True,
                        verbose_name="activate package api response data",
                    ),
                ),
            ],
        ),
    ]
