# Generated by Django 4.2.10 on 2024-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rnr", "0014_userroompurchaseconfirmresponselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rnrroomreservation",
            name="user",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
